language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - touch ./database/lara
  - php artisan key:generate
  - php artisan migrate:refresh --seed
script:
  - vendor/bin/phpunit
